import { DurableObject } from "cloudflare:workers";
interface Env { DB:D1Database; ASSETS:Fetcher; GAME_ROOM:DurableObjectNamespace<GameRoom>; }
const json=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{"content-type":"application/json; charset=utf-8"}});
function cookie(n:string,v:string,a:number){return `${n}=${encodeURIComponent(v)}; Max-Age=${a}; Path=/; HttpOnly; Secure; SameSite=Lax`}
function getCookie(r:Request,n:string){const x=r.headers.get("Cookie")||"";const y=x.split(";").map(v=>v.trim()).find(v=>v.startsWith(n+"="));return y?decodeURIComponent(y.slice(n.length+1)):null}
const uid=()=>crypto.randomUUID();
function b64(b:Uint8Array){let s="";for(const x of b)s+=String.fromCharCode(x);return btoa(s)}
function unb64(s:string){const x=atob(s);return Uint8Array.from(x,c=>c.charCodeAt(0))}
async function derive(p:string,s:Uint8Array){const k=await crypto.subtle.importKey("raw",new TextEncoder().encode(p),"PBKDF2",false,["deriveBits"]);return new Uint8Array(await crypto.subtle.deriveBits({name:"PBKDF2",salt:s,iterations:100000,hash:"SHA-256"},k,256))}
async function hash(p:string){const s=crypto.getRandomValues(new Uint8Array(16));return `${b64(s)}.${b64(await derive(p,s))}`}
async function verify(p:string,v:string){const [a,b]=v.split(".");if(!a||!b)return false;const x=unb64(b),y=await derive(p,unb64(a));if(x.length!==y.length)return false;let d=0;for(let i=0;i<x.length;i++)d|=x[i]^y[i];return d===0}
async function user(r:Request,e:Env){const t=getCookie(r,"mmo_session");if(!t)return null;const z=await e.DB.prepare(`SELECT a.id account_id,a.username,c.id character_id,c.name character_name,c.level,c.exp,c.gold,c.map FROM sessions s JOIN accounts a ON a.id=s.account_id JOIN characters c ON c.account_id=a.id WHERE s.token=? AND s.expires_at>?`).bind(t,Date.now()).first<any>();return z?{accountId:z.account_id,username:z.username,character:{id:z.character_id,name:z.character_name,level:z.level,exp:z.exp,gold:z.gold,map:z.map}}:null}
async function session(e:Env,accountId:string,username:string,c:any){const t=b64(crypto.getRandomValues(new Uint8Array(32))),now=Date.now();await e.DB.prepare("INSERT INTO sessions(token,account_id,expires_at,created_at) VALUES(?,?,?,?)").bind(t,accountId,now+2592000000,now).run();const r=json({ok:true,user:{username,character:{id:c.id,name:c.name,level:c.level,exp:c.exp,gold:c.gold,map:c.map}}});r.headers.append("Set-Cookie",cookie("mmo_session",t,2592000));return r}
async function register(r:Request,e:Env){const b=await r.json<any>(),u=String(b.username||"").trim().toLowerCase(),p=String(b.password||""),n=String(b.characterName||"").trim();if(!/^[a-z0-9_]{3,20}$/.test(u))return json({error:"Username 3-20 karakter: a-z, 0-9, _."},400);if(p.length<8||p.length>128)return json({error:"Password harus 8-128 karakter."},400);if(!/^[A-Za-z0-9_ ]{3,20}$/.test(n))return json({error:"Nama karakter 3-20 karakter."},400);if(await e.DB.prepare("SELECT id FROM accounts WHERE username=?").bind(u).first())return json({error:"Username sudah digunakan."},409);if(await e.DB.prepare("SELECT id FROM characters WHERE name=?").bind(n).first())return json({error:"Nama karakter sudah digunakan."},409);const aid=uid(),cid=uid(),now=Date.now();try{await e.DB.batch([e.DB.prepare("INSERT INTO accounts(id,username,password_hash,created_at) VALUES(?,?,?,?)").bind(aid,u,await hash(p),now),e.DB.prepare("INSERT INTO characters(id,account_id,name,created_at) VALUES(?,?,?,?)").bind(cid,aid,n,now)])}catch{return json({error:"Gagal membuat akun."},409)}return session(e,aid,u,{id:cid,name:n,level:1,exp:0,gold:100,map:"village"})}
async function login(r:Request,e:Env){const b=await r.json<any>(),u=String(b.username||"").trim().toLowerCase(),p=String(b.password||""),a=await e.DB.prepare("SELECT id,username,password_hash FROM accounts WHERE username=?").bind(u).first<any>();if(!a||!(await verify(p,a.password_hash)))return json({error:"Username atau password salah."},401);const c=await e.DB.prepare("SELECT id,name,level,exp,gold,map FROM characters WHERE account_id=?").bind(a.id).first<any>();return session(e,a.id,a.username,c)}
export class GameRoom extends DurableObject<Env>{
  positions=new Map<string,{x:number,y:number,name:string}>();
  constructor(ctx:DurableObjectState,env:Env){super(ctx,env);ctx.setWebSocketAutoResponse(new WebSocketRequestResponsePair("ping","pong"))}
  async fetch(r:Request){if(r.headers.get("Upgrade")!=="websocket")return new Response("GameRoom OK");const id=r.headers.get("x-player-id"),name=r.headers.get("x-player-name");if(!id||!name)return new Response("Unauthorized",{status:401});const pair=new WebSocketPair(),server=pair[1];this.ctx.acceptWebSocket(server);server.serializeAttachment({id,name});const p={x:400+Math.floor(Math.random()*160),y:300+Math.floor(Math.random()*120),name};this.positions.set(id,p);server.send(JSON.stringify({type:"welcome",playerId:id,players:[...this.positions].map(([i,v])=>({id:i,...v}))}));this.broadcast(JSON.stringify({type:"join",id,...p}),[server]);return new Response(null,{status:101,webSocket:pair[0]})}
  webSocketMessage(ws:WebSocket,msg:string|ArrayBuffer){const a=ws.deserializeAttachment() as {id:string,name:string}|null;if(!a||typeof msg!=="string")return;let d:any;try{d=JSON.parse(msg)}catch{return}if(d?.type!=="move")return;const x=Number(d.x),y=Number(d.y),old=this.positions.get(a.id);if(!old||!Number.isFinite(x)||!Number.isFinite(y))return;const p={x:Math.max(0,Math.min(2000,Math.round(x))),y:Math.max(0,Math.min(1200,Math.round(y))),name:old.name};this.positions.set(a.id,p);this.broadcast(JSON.stringify({type:"move",id:a.id,x:p.x,y:p.y}),[ws])}
  webSocketClose(ws:WebSocket){this.leave(ws)} webSocketError(ws:WebSocket){this.leave(ws)}
  leave(ws:WebSocket){const a=ws.deserializeAttachment() as {id:string}|null;if(!a)return;this.positions.delete(a.id);this.broadcast(JSON.stringify({type:"leave",id:a.id}),[ws])}
  broadcast(m:string,ex:WebSocket[]=[]){const s=new Set(ex);for(const w of this.ctx.getWebSockets())if(!s.has(w))try{w.send(m)}catch{}}
}
export default {async fetch(r:Request,e:Env){const u=new URL(r.url);if(u.pathname==="/api/register"&&r.method==="POST")return register(r,e);if(u.pathname==="/api/login"&&r.method==="POST")return login(r,e);if(u.pathname==="/api/me"&&r.method==="GET")return json({authenticated:!!(await user(r,e)),user:await user(r,e)});if(u.pathname==="/api/logout"&&r.method==="POST"){const t=getCookie(r,"mmo_session");if(t)await e.DB.prepare("DELETE FROM sessions WHERE token=?").bind(t).run();const x=json({ok:true});x.headers.append("Set-Cookie",cookie("mmo_session","",0));return x}if(u.pathname==="/ws"){const a=await user(r,e);if(!a)return json({error:"Login diperlukan."},401);const room=e.GAME_ROOM.get(e.GAME_ROOM.idFromName("map:village"));const h=new Headers(r.headers);h.set("x-player-id",a.character.id);h.set("x-player-name",a.character.name);return room.fetch(new Request(r,{headers:h}))}return e.ASSETS.fetch(r)}};
